export const FETCH_STORIES_REQUEST = 'FETCH_STORIES_REQUEST';
export const FETCH_STORIES_SUCCESS = 'FETCH_STORIES_SUCCESS';
export const FETCH_STORIES_ERROR = 'FETCH_STORIES_ERROR';

export const FETCH_STORY_PREVIEW_REQUEST = 'FETCH_STORY_PREVIEW_REQUEST';
export const FETCH_STORY_PREVIEW_SUCCESS = 'FETCH_STORY_PREVIEW_SUCCESS';
export const FETCH_STORY_PREVIEW_ERROR = 'FETCH_STORY_PREVIEW_ERROR';

export const SELECT_STORY_PREVIEW = 'SELECT_STORY_PREVIEW';

export const CREATE_STORY_REQUEST = 'CREATE_STORY_REQUEST';
export const CREATE_STORY_SUCCESS = 'CREATE_STORY_SUCCESS';
export const CREATE_STORY_ERROR = 'CREATE_STORY_ERROR';

export const UPDATE_STORY_REQUEST = 'UPDATE_STORY_REQUEST';
export const UPDATE_STORY_SUCCESS = 'UPDATE_STORY_SUCCESS';
export const UPDATE_STORY_ERROR = 'UPDATE_STORY_ERROR';

export const PROCESS_STORY_REQUEST = 'PROCESS_STORY_REQUEST';
export const PROCESS_STORY_SUCCESS = 'PROCESS_STORY_SUCCESS';
export const PROCESS_STORY_ERROR = 'PROCESS_STORY_ERROR';
